### ISSUE TITLE
v8worker.DiscardSendSync doesn't exist

### ISSUE THREAD

**Issue by jgautheron** [nmerouze/gojs#2]
`DiscardSendSync` is only defined in a [test](https://github.com/ry/v8worker/blob/master/worker_test.go#L13).

I made the following changes in `pool.go` and then it worked fine:

``` diff
+func DiscardSendSync(msg string) string { return "" }
+
 func newWorker(pool *workerPool, fn func(*Worker)) *Worker {
        w := new(Worker)

        v8w := v8worker.New(func(msg string) {
                w.ch <- msg
-       }, v8worker.DiscardSendSync)
+       }, DiscardSendSync)

        w.Worker = v8w
```

**Comment by nmerouze** [comment]
Thanks for the issue. v8worker removed it a month ago, it was ok before. I've pushed the fix.
