### ISSUE TITLE
is this production ready

### ISSUE THREAD

**Issue by johnjerrico** [nmerouze/gojs#3]
Hi, 
I'm really interested in your solution, however is this production ready ?

**Comment by nmerouze** [comment]
@johnjerrico It depends what you mean by production-ready. The code is pretty stable and should work well but I don't think anyone use it in production.

**Comment by johnjerrico** [comment]
@nmerouze thanks for replying,
 I've been viewing your code and it seems to be dependent to v8worker and sadly it seems to be stall in progress is it stable up to a point where I can use it with latest reactjs code; hmm I'm thinking an alternative by using v8 (c++) from google directly, is it a good idea ?
sorry, to ask you like this I've been asking around and no one seems to be replying. hmm  I need this to do a server-rendering  reactjs.

**Comment by nmerouze** [comment]
@johnjerrico v8worker is a thin wrapper around v8, so you could just fork v8worker and update to the latest version of v8 yourself. But even a year old v8 can run the latest reactjs.

**Comment by johnjerrico** [comment]
@nmerouze thanx alot

**Comment by olebedev** [comment]
Hi @johnjerrico,

> hmm I'm thinking an alternative by using v8 (c++) from google directly, is it a good idea ?

Please, take a look - https://github.com/olebedev/go-starter-kit

**Comment by johnjerrico** [comment]
Hi @olebedev thanks, I'm trying to avoid ducktape due to lots of bad reviews

**Comment by olebedev** [comment]
@johnjerrico, interesting. Any links?

**Comment by johnjerrico** [comment]
HI @olebedev here are some 
[blog](http://blog.dimroc.com/2016/02/05/not-quite-utopia-golang-isomorphic-react/)
[reddit](https://www.reddit.com/r/golang/comments/3bqm94/isomorphic_react_with_go/)

**Comment by olebedev** [comment]
@johnjerrico,

Oh.., seems you haven't been read this links. Why do I think so?

Blog post tells us that the isomorphic apps are non-trivial in general, that's true. All the problems related isomorphic approach and it's a hard engineering challenge, not depending on a platform you use(node, ruby, python, golang, etc). There is only one golang-related issue - native dependencies(duktape). Yup, it's a binding for the C code. But it's not an isomorphic issue at all and of course, not a duktape issue. Moreover, as you can see, selfjs is based on native c++ code too. 
So, you have at least two reasons forget about isomorphic apps as well as about selfjs, b/c it's a native package ;) but you still looking and it's at least non-logical.

I have some comments at reddit's post. Duktape is a pretty good and stable piece of software as well as V8 of course. It's slower than V8, but the benefit that go-duktape is go get-able but selfjs is not.

Have a good engineering. Cheers.

**Comment by johnjerrico** [comment]
@olebedev thanks a lot for your input, to be honest I only skim the post; I've been looking for this kind of input since last week without any feedback, I really appreciate for your time to make this input, thanks a lot

**Comment by nmerouze** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/Qzbl30Qv/60-test)
